displayName=Unsired Tracker
author=H4waiianPunch
description=Stats for Unsireds
support=https://github.com/H4waiianPunch/UnsiredTracker#unsired-tracker
tags=abyssalsire,sire,unsired,tracker,stat
plugins=com.UnsiredTracker.UnsiredTrackerPlugin
